export const vectorLayers = [
    "Barlos",
    "Baxor",
    "Beruniy",
    "Chifokor",
    "Chinobod",
    "Dehqonobod",
    "Guliston",
    "Kulbekov",
    "Mirzacho'l",
    "MUlugbek",
    "Mustaqillik5yil",
    "Navruz",
    "Oqoltin",
    "OqoltinShaxarchasi",
    "Oxunboboev",
    "Sirdaryo baliqchilik",
    "T.Axmedov",
    "Toshkent",
    "Urmon",
    "Urmon2uch",
    "Yangiobod",
    "Yangiyer",
    "Yunusov"
]